script:
    - mkdir -p travis_checkout
    - cd travis_checkout
    - git clone https://github.com/santazhang/base-utils.git
    - git clone https://github.com/santazhang/sstable.git
    - cd base-utils
    - ./waf configure
    - ./waf
    - cd ../sstable
    - ./waf configure
    - ./waf
    - ./build/unittest
